### ISSUE TITLE
Display usedBy depencies in ressources

### ISSUE THREAD

**Issue by nborie** [cisstech/platon#85]
The goal of this issue is to add a very small summary of ressources using the current ressources in the search view.

Here is an exemple of ressources search view :

![Capture d’écran du 2024-02-11 16-03-03](https://github.com/cisstech/platon/assets/6042616/9d908872-305c-4d97-a5c6-8b5f60793b70)

There is a template exercice (the word template is used with MAJ to emphase the importance). Then, there is some Python exercises using the previous template. It could be fine to add the following line for the first exercice.

`> Cette ressource est actuellement utilisée par 8 autres exercices ( < toggle button > déplier la liste)`

When one click on the button (toggle on/off), the list of all ressources using the current ressource appears or disappers.

For the screenshot, this will give for the first ressource named "(TEMPLATE)"

* Doctest challenge : factorielle d'un entier
* Doctest challenge : un hello world
* Doctest challenge : moyenne entière des positifs
* Doctest challenge : indice du dernier max parmi les positifs
* Doctest challenge : les trois plus grands
* ...

Each element of this list could be a link the pointed exercice.

This feature is important for exercices. For activities, it is not very relevant since one knows that activities are composed by some exercices. This features is especially important for template. This will inform rapidly any contributor about the impact of modifying a template. 

Whenever an exercice is final (it is never included by another exercices), the best is to not diplay anything. When an exercice is used by at least one other ressource of type exercice, it could be very interesting to add this small depencies summary in the search view.

In my opinion, the best place where putting these information is after the tags but before the "Éditer" and "Prévisualiser" buttons in search views.

**Comment by mciissee** [comment]
@nborie This is not really difficult to implements since the backend is already ready for such use cases. I will implements the frontend in the following weeks.

A side note, for template exercises, I think that you can use main.plc files use the "Configurable" filter.

<img width="379" alt="Capture d’écran 2024-02-11 à 16 42 23" src="https://github.com/cisstech/platon/assets/30326262/b335acda-6d5c-486d-81d0-7db3fd7656f6">
<img width="1297" alt="Capture d’écran 2024-02-11 à 16 44 00" src="https://github.com/cisstech/platon/assets/30326262/6abc09e0-950a-4a12-bcb2-edc15d4a31fb">

Here is a link to the documentation of this feature : 
https://cisstech.github.io/platon/docs/main/doc/programing/exercise/config
